version: '3.2'
services:
 cadvisor:
  image: google/cadvisor:latest  
  volumes:
   - "/:/rootfs"
   - "/var/run:/var/run"
   - "/sys:/sys"
   - "/var/lib/docker/:/var/lib/docker/"
  ports:
   - target: 8080
     published: 8080
     mode: host
  deploy:
   mode: global