version: '3.1'

services:
    mysql:
        image: mysql:latest
        environment: 
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_PASSWORD_FILE: "/run/secrets/mysql_root_password"
            MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"
        secrets:
            - source: password
              target: mysql_root_password
        deploy:
            placement:
                constraints:
                    - node.role==manager
secrets:
    password:
        external:
            name: mysql_root_password
